version: 0.2

env:
  variables:
    SENTRY_ORG: 'usc-ict-ls'
    SENTRY_PROJECT: 'mentor-uploader'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - pyenv global $PYTHON_38_VERSION
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install pytest && pip3 install poetry
      - poetry install --no-root
      - n 16 # workaround https://github.com/aws/aws-codebuild-docker-images/issues/490
      - NODE_ENV=dev npm ci

  build:
    commands:
      - echo Checking formatting
      - flake8 .
      # TODO 
      # - echo Running tests

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
cache:
  paths:
    - '/root/venv/**/*'
    - '/root/.cache/pip/**/*'
    - '/root/.cache/pypoetry/virtualenvs/**/*'
