version: 0.2

env:
  variables:
    SENTRY_ORG: 'usc-ict-ls'
    SENTRY_PROJECT: 'mentor-uploader'

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - NODE_ENV=dev npm ci
      - pyenv global $PYTHON_38_VERSION
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install flake8

  build:
    commands:
      - echo Checking formatting
      - flake8 .
      # TODO 
      # - echo Running tests

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
