Response5xx:
  Type: 'AWS::ApiGateway::GatewayResponse'
  Properties:
    ResponseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: 'method.request.header.origin'
    ResponseType: DEFAULT_5XX
    RestApiId:
      Ref: 'ApiGatewayRestApi'
Response4xx:
  Type: 'AWS::ApiGateway::GatewayResponse'
  Properties:
    ResponseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: 'method.request.header.origin'
    ResponseType: DEFAULT_4XX
    RestApiId:
      Ref: 'ApiGatewayRestApi'
